line-length = 120
indent-width = 4
target-version = "py311"

exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "venv",
    "tests/*",
    "examples/*",
    "notebooks/*",
]

[lint]
select = ["E", "F", "I", "B", "C4", "ARG", "SIM", "ERA", "PL", "RUF"]
ignore = ["PLR0915"]
fixable = ["ALL"]
unfixable = []
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"

[per-file-ignores]
"notebooks/**/*" = [
    "F401", # unused imports
    "F811", # redefinition of unused name
    "F821", # undefined name
    "F841", # unused variable
    "E402", # module level import not at top of file
    "E501", # line too long
]
"**/*.ipynb" = ["F401", "F811", "F821", "F841", "E402", "E501"]
"*.ipynb" = ["F401", "F811"]
